-- 코드를 입력하세요
SELECT AO.ANIMAL_ID, AO.ANIMAL_TYPE, AO.NAME
FROM ANIMAL_OUTS AO JOIN ANIMAL_INS AI ON AO.ANIMAL_ID = AI.ANIMAL_ID
WHERE (AO.SEX_UPON_OUTCOME LIKE '%SPAYED%' OR AO.SEX_UPON_OUTCOME LIKE '%NEUTERED%') AND
AI.SEX_UPON_INTAKE LIKE '%INTACT%'